"""add extraction jobs table

Revision ID: 14f57b4ae0bc
Revises: ce0581432237
Create Date: 2026-09-04 23:22:39.818752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '14f57b4ae0bc'
down_revision: Union[str, Sequence[str], None] = 'ce0581432237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_jobs_document_id'), 'extraction_jobs', ['document_id'], unique=False)
    # ### end Alembic commands ###
    #
    # Autogenerate also proposed a few unrelated diffs (document_pages
    # JSON column types, a documents self-referential FK, an
    # extraction_models NOT NULL change) sourced purely from this local
    # dev SQLite file's own ALTER-TABLE history — every one of those
    # already matches the current models via the baseline migration's
    # create_table calls on a fresh database, so they were removed here
    # rather than re-applied.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extraction_jobs_document_id'), table_name='extraction_jobs')
    op.drop_table('extraction_jobs')
    # ### end Alembic commands ###
