"""baseline schema

Revision ID: ce0581432237
Revises: 
Create Date: 2026-09-04 21:55:43.353715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce0581432237'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('processing_status', sa.String(length=30), nullable=False),
    sa.Column('processed_page_count', sa.Integer(), nullable=False),
    sa.Column('ocr_required_page_count', sa.Integer(), nullable=False),
    sa.Column('ocr_completed_page_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('document_type', sa.String(length=60), nullable=True),
    sa.Column('industry', sa.String(length=60), nullable=True),
    sa.Column('contract_side', sa.String(length=20), nullable=True),
    sa.Column('document_language', sa.String(length=40), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('document_status', sa.String(length=30), nullable=True),
    sa.Column('parent_document_id', sa.String(length=36), nullable=True),
    sa.Column('parent_relationship_type', sa.String(length=30), nullable=True),
    sa.Column('parent_relationship_confidence', sa.Float(), nullable=True),
    sa.Column('parent_relationship_matched_on', sa.String(length=20), nullable=True),
    sa.Column('parent_relationship_status', sa.String(length=20), nullable=True),
    sa.Column('parent_relationship_reasons', sa.JSON(), nullable=True),
    sa.Column('parent_relationship_detection_method', sa.String(length=20), nullable=True),
    sa.Column('processing_duration_seconds', sa.Float(), nullable=True),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promoted_by', sa.String(length=120), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['parent_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_documents_checksum_sha256'), 'documents', ['checksum_sha256'], unique=False)
    op.create_table('extraction_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('document_types', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classification_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('field_changed', sa.String(length=30), nullable=False),
    sa.Column('previous_value', sa.String(length=120), nullable=True),
    sa.Column('new_value', sa.String(length=120), nullable=True),
    sa.Column('changed_by', sa.String(length=120), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classification_audit_log_document_id'), 'classification_audit_log', ['document_id'], unique=False)
    op.create_table('document_addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('address_type', sa.String(length=40), nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=True),
    sa.Column('street', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=15), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_addresses_document_id'), 'document_addresses', ['document_id'], unique=False)
    op.create_table('document_amendment_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('amendment_number', sa.String(length=30), nullable=False),
    sa.Column('effective_date', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_amendment_history_document_id'), 'document_amendment_history', ['document_id'], unique=False)
    op.create_table('document_clause_references',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('clause_family', sa.String(length=10), nullable=False),
    sa.Column('clause_number', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('effective_date', sa.String(length=40), nullable=True),
    sa.Column('alternate', sa.String(length=20), nullable=True),
    sa.Column('deviation', sa.String(length=120), nullable=True),
    sa.Column('variation_effective_date', sa.String(length=40), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_clause_references_document_id'), 'document_clause_references', ['document_id'], unique=False)
    op.create_table('document_clauses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('clause_type', sa.String(length=40), nullable=False),
    sa.Column('classification', sa.String(length=120), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('value_summary', sa.String(length=200), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_clauses_document_id'), 'document_clauses', ['document_id'], unique=False)
    op.create_table('document_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=False),
    sa.Column('role_title', sa.String(length=200), nullable=True),
    sa.Column('phone_area_code', sa.String(length=5), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('phone_extension', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_contacts_document_id'), 'document_contacts', ['document_id'], unique=False)
    op.create_table('document_delivery_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('clin', sa.String(length=20), nullable=True),
    sa.Column('delivery_date', sa.String(length=40), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('ship_to_address', sa.Text(), nullable=True),
    sa.Column('dodaac', sa.String(length=10), nullable=True),
    sa.Column('cage_code', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_delivery_schedule_document_id'), 'document_delivery_schedule', ['document_id'], unique=False)
    op.create_table('document_detected_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('target_key', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('pages_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_examples_json', sa.JSON(), nullable=False),
    sa.Column('parent_section', sa.String(length=255), nullable=True),
    sa.Column('columns_json', sa.JSON(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('suggested_instruction', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'target_key', name='uq_document_detected_target_key')
    )
    op.create_index(op.f('ix_document_detected_targets_document_id'), 'document_detected_targets', ['document_id'], unique=False)
    op.create_table('document_funding_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('acrn', sa.String(length=10), nullable=True),
    sa.Column('line_of_accounting', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_funding_lines_document_id'), 'document_funding_lines', ['document_id'], unique=False)
    op.create_table('document_insurance_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('coverage_type', sa.String(length=200), nullable=False),
    sa.Column('minimum_amount', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_insurance_requirements_document_id'), 'document_insurance_requirements', ['document_id'], unique=False)
    op.create_table('document_key_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('position_title', sa.String(length=200), nullable=False),
    sa.Column('pir', sa.String(length=40), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=True),
    sa.Column('monthly_amount', sa.Float(), nullable=True),
    sa.Column('pws_section', sa.String(length=80), nullable=True),
    sa.Column('wawf_field', sa.String(length=120), nullable=True),
    sa.Column('wawf_value', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_key_positions_document_id'), 'document_key_positions', ['document_id'], unique=False)
    op.create_table('document_line_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('clin', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('is_maximum', sa.Boolean(), nullable=False),
    sa.Column('period_label', sa.String(length=80), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_line_items_document_id'), 'document_line_items', ['document_id'], unique=False)
    op.create_table('document_metadata_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('field_group', sa.String(length=30), nullable=False),
    sa.Column('field_key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extraction_method', sa.String(length=30), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('human_approved', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_metadata_fields_document_id'), 'document_metadata_fields', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_metadata_fields_field_key'), 'document_metadata_fields', ['field_key'], unique=False)
    op.create_table('document_order_ranges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('naics_code', sa.String(length=10), nullable=True),
    sa.Column('minimum_amount', sa.Float(), nullable=True),
    sa.Column('maximum_amount', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_order_ranges_document_id'), 'document_order_ranges', ['document_id'], unique=False)
    op.create_table('document_pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('page_label', sa.String(length=50), nullable=True),
    sa.Column('native_text', sa.Text(), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('final_text', sa.Text(), nullable=False),
    sa.Column('form_fields_json', sa.JSON(), nullable=True),
    sa.Column('tables_json', sa.JSON(), nullable=True),
    sa.Column('has_tables', sa.Boolean(), nullable=False),
    sa.Column('has_form_fields', sa.Boolean(), nullable=False),
    sa.Column('is_scanned', sa.Boolean(), nullable=False),
    sa.Column('text_length', sa.Integer(), nullable=False),
    sa.Column('extraction_method', sa.String(length=30), nullable=False),
    sa.Column('requires_ocr', sa.Boolean(), nullable=False),
    sa.Column('ocr_attempted', sa.Boolean(), nullable=False),
    sa.Column('ocr_succeeded', sa.Boolean(), nullable=False),
    sa.Column('ocr_language', sa.String(length=30), nullable=True),
    sa.Column('ocr_error', sa.Text(), nullable=True),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('text_block_count', sa.Integer(), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.Column('text_coverage_ratio', sa.Float(), nullable=False),
    sa.Column('image_coverage_ratio', sa.Float(), nullable=False),
    sa.Column('page_width', sa.Float(), nullable=False),
    sa.Column('page_height', sa.Float(), nullable=False),
    sa.Column('extraction_status', sa.String(length=30), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_document_page_number')
    )
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_table('document_performance_periods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('period_label', sa.String(length=80), nullable=False),
    sa.Column('start_date', sa.String(length=40), nullable=True),
    sa.Column('end_date', sa.String(length=40), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_performance_periods_document_id'), 'document_performance_periods', ['document_id'], unique=False)
    op.create_table('document_signatures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('party_name', sa.String(length=200), nullable=False),
    sa.Column('signatory_name', sa.String(length=200), nullable=False),
    sa.Column('signatory_title', sa.String(length=200), nullable=False),
    sa.Column('signed', sa.Boolean(), nullable=False),
    sa.Column('signature_date', sa.String(length=40), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_signatures_document_id'), 'document_signatures', ['document_id'], unique=False)
    op.create_table('document_structure_summaries',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('document_family', sa.String(length=80), nullable=False),
    sa.Column('document_family_label', sa.String(length=120), nullable=False),
    sa.Column('document_family_confidence', sa.Float(), nullable=False),
    sa.Column('content_stats_json', sa.JSON(), nullable=False),
    sa.Column('detected_contacts_json', sa.JSON(), nullable=False),
    sa.Column('detected_obligations_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('document_wawf_instructions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=200), nullable=False),
    sa.Column('instruction_value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_wawf_instructions_document_id'), 'document_wawf_instructions', ['document_id'], unique=False)
    op.create_table('extraction_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['extraction_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_fields_model_id'), 'extraction_fields', ['model_id'], unique=False)
    op.create_table('metadata_field_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('field_key', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=120), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_field_audit_log_document_id'), 'metadata_field_audit_log', ['document_id'], unique=False)
    op.create_index(op.f('ix_metadata_field_audit_log_field_key'), 'metadata_field_audit_log', ['field_key'], unique=False)
    op.create_table('relationship_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('previous_parent_id', sa.String(length=36), nullable=True),
    sa.Column('new_parent_id', sa.String(length=36), nullable=True),
    sa.Column('previous_relationship_type', sa.String(length=30), nullable=True),
    sa.Column('new_relationship_type', sa.String(length=30), nullable=True),
    sa.Column('changed_by', sa.String(length=120), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_audit_log_document_id'), 'relationship_audit_log', ['document_id'], unique=False)
    op.create_table('page_text_blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_page_id', sa.Integer(), nullable=False),
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=30), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('x0', sa.Float(), nullable=False),
    sa.Column('y0', sa.Float(), nullable=False),
    sa.Column('x1', sa.Float(), nullable=False),
    sa.Column('y1', sa.Float(), nullable=False),
    sa.Column('extraction_method', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['document_page_id'], ['document_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_text_blocks_document_page_id'), 'page_text_blocks', ['document_page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_text_blocks_document_page_id'), table_name='page_text_blocks')
    op.drop_table('page_text_blocks')
    op.drop_index(op.f('ix_relationship_audit_log_document_id'), table_name='relationship_audit_log')
    op.drop_table('relationship_audit_log')
    op.drop_index(op.f('ix_metadata_field_audit_log_field_key'), table_name='metadata_field_audit_log')
    op.drop_index(op.f('ix_metadata_field_audit_log_document_id'), table_name='metadata_field_audit_log')
    op.drop_table('metadata_field_audit_log')
    op.drop_index(op.f('ix_extraction_fields_model_id'), table_name='extraction_fields')
    op.drop_table('extraction_fields')
    op.drop_index(op.f('ix_document_wawf_instructions_document_id'), table_name='document_wawf_instructions')
    op.drop_table('document_wawf_instructions')
    op.drop_table('document_structure_summaries')
    op.drop_index(op.f('ix_document_signatures_document_id'), table_name='document_signatures')
    op.drop_table('document_signatures')
    op.drop_index(op.f('ix_document_performance_periods_document_id'), table_name='document_performance_periods')
    op.drop_table('document_performance_periods')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_document_order_ranges_document_id'), table_name='document_order_ranges')
    op.drop_table('document_order_ranges')
    op.drop_index(op.f('ix_document_metadata_fields_field_key'), table_name='document_metadata_fields')
    op.drop_index(op.f('ix_document_metadata_fields_document_id'), table_name='document_metadata_fields')
    op.drop_table('document_metadata_fields')
    op.drop_index(op.f('ix_document_line_items_document_id'), table_name='document_line_items')
    op.drop_table('document_line_items')
    op.drop_index(op.f('ix_document_key_positions_document_id'), table_name='document_key_positions')
    op.drop_table('document_key_positions')
    op.drop_index(op.f('ix_document_insurance_requirements_document_id'), table_name='document_insurance_requirements')
    op.drop_table('document_insurance_requirements')
    op.drop_index(op.f('ix_document_funding_lines_document_id'), table_name='document_funding_lines')
    op.drop_table('document_funding_lines')
    op.drop_index(op.f('ix_document_detected_targets_document_id'), table_name='document_detected_targets')
    op.drop_table('document_detected_targets')
    op.drop_index(op.f('ix_document_delivery_schedule_document_id'), table_name='document_delivery_schedule')
    op.drop_table('document_delivery_schedule')
    op.drop_index(op.f('ix_document_contacts_document_id'), table_name='document_contacts')
    op.drop_table('document_contacts')
    op.drop_index(op.f('ix_document_clauses_document_id'), table_name='document_clauses')
    op.drop_table('document_clauses')
    op.drop_index(op.f('ix_document_clause_references_document_id'), table_name='document_clause_references')
    op.drop_table('document_clause_references')
    op.drop_index(op.f('ix_document_amendment_history_document_id'), table_name='document_amendment_history')
    op.drop_table('document_amendment_history')
    op.drop_index(op.f('ix_document_addresses_document_id'), table_name='document_addresses')
    op.drop_table('document_addresses')
    op.drop_index(op.f('ix_classification_audit_log_document_id'), table_name='classification_audit_log')
    op.drop_table('classification_audit_log')
    op.drop_table('extraction_models')
    op.drop_index(op.f('ix_documents_checksum_sha256'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
